- id: goimports
  name: 'goimports'
  language: system
  entry: goimports -w
  files: '\.go$'
  exclude: '^vendor.*$'
  description: "Run goimports to format code and sort imports"

- id: gometalinter
  name: 'gometalinter'
  language: system
  entry: gometalinter ./...
  description: "Run gometalinter to check code style"
